### ISSUE TITLE
Implement ntp

### ISSUE THREAD

**Issue by bradbeam** [autonomy/talos#279]
Some resources:
- https://medium.com/learning-the-go-programming-language/lets-make-an-ntp-client-in-go-287c4b9a969f
- https://github.com/beevik/ntp

**Comment by andrewrynhard** [comment]
We should make use of the kernel's auto configuration for the nth servers: https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/Documentation/filesystems/nfs/nfsroot.txt#L202-L206

**Comment by vbmade2000** [comment]
Is this issue about creating a new NTP Server or a client in Go ?

**Comment by andrewrynhard** [comment]
@vbmade2000 A client. What we need/want is a pure Golang implementation of an NTP client. Etcd is the driver here. Time sync is gonnna be crucial to ensure it works correctly on Talos.

**Comment by andrewrynhard** [comment]
@vbmade2000 Also, you can email me to add you to our slack if you would like!

**Comment by vbmade2000** [comment]
@andrewrynhard Sure. It is mlvora.2010@gmail.com.

**Comment by andrewrynhard** [comment]
@vbmade2000 Great, invite sent 👍.

**Comment by bradbeam** [comment]
gontpd seems like a very solid implementation and I think it'd be a great candidate. Unfortunately there's no license associated with the project yet. 
Logged https://github.com/mengzhuo/gontpd/issues/6

**Comment by vbmade2000** [comment]
@andrewrynhard I am extremely sorry I couldn't work on this. I had lot of struggle in setting up `Talos`.

**Comment by andrewrynhard** [comment]
@vbmade2000 no worries at all. We are making big strides in making Talos much more approachable. When I first announced it, it was not in the best shape for usability. I'd be happy to help you get up and running with Talos some time in slack.

**Comment by vbmade2000** [comment]
@andrewrynhard I'll surely get back to work on Talos after getting some office work burden off. Thanks for understanding.
