### ISSUE TITLE
gitmeta - command not found

### ISSUE THREAD

**Issue by candrews67** [autonomy/talos#342]
you have a dependency on 'git-meta'. I got:
make: gitmeta : command not found

I am installing https://github.com/twosigma/git-meta.git. Hoping that is correct.

Thanks!

**Comment by rsmitty** [comment]
Hey @candrews67, should be an internal repo actually. https://github.com/autonomy/gitmeta is what you want.

**Comment by candrews67** [comment]
Thanks!
-------- Original message --------From: Spencer Smith <notifications@github.com> Date: 2/15/19  2:02 PM  (GMT-06:00) To: autonomy/talos <talos@noreply.github.com> Cc: Carl <carl@andrewsfamily.us>, Mention <mention@noreply.github.com> Subject: Re: [autonomy/talos] gitmeta - command not found (#342) Hey @candrews67, should be an internal repo actually. https://github.com/autonomy/gitmeta is what you want.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/autonomy/talos","title":"autonomy/talos","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/autonomy/talos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rsmitty in #342: Hey @candrews67, should be an internal repo actually. https://github.com/autonomy/gitmeta is what you want. "}],"action":{"name":"View Issue","url":"https://github.com/autonomy/talos/issues/342#issuecomment-464181153"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/autonomy/talos/issues/342#issuecomment-464181153",
"url": "https://github.com/autonomy/talos/issues/342#issuecomment-464181153",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
