### ISSUE TITLE
How do I run osctl?

### ISSUE THREAD

**Issue by makzpj** [autonomy/talos#354]
I'd appreciate some help with this.

I've managed to install Talos to /dev/sdb. Upon booting, it looks for the master yaml file, but to generate that I need to run osctl. How do I get to run that? I'm confused.

**Comment by andrewrynhard** [comment]
Hey @makzpj.

You can download `osctl` from the [releases](https://github.com/autonomy/talos/releases) page. The `osctl` binary is not strictly required, but it does make things easier when generating the certs. We have some guidance on how to create the config file and certs in the [documentation](https://talos.autonomy.io). Also feel free to email me so I can add you to our slack.

**Comment by makzpj** [comment]
Thanks! that was quick, it's what I was looking for.
