### ISSUE TITLE
Node crashes with invalid config

### ISSUE THREAD

**Issue by unixfox** [autonomy/talos#356]
Hello,

I'm currently trying to test talos on a dev environment. My environment is an ArchLinux home server with KVM (virt manager for managing it).
I've followed these three guides:
- https://talos.autonomy.io/configuration/osd/
- https://talos.autonomy.io/configuration/masters/
- https://talos.autonomy.io/examples/kvm/

Here the full complete list of commands that I ran from these guides:
```
osctl gen ca --hours 17520 --organization orga
osctl gen key --name master
osctl gen csr --ip 192.168.1.50 --key master.key
osctl gen crt --hours 17520 --ca orga --csr master.csr --name master
osctl gen key --name emilien
osctl gen csr --ip 192.168.1.51 --key emilien.key
osctl gen crt --hours 17520 --ca orga --csr
osctl gen crt --hours 17520 --ca orga --csr emilien.csr --name emilien
touch master.yaml
osctl inject os --crt orga.crt --key orga.key master.yaml 
osctl inject identity --crt orga.crt --key orga.key master.yaml 
osctl gen ca --rsa --hours 17520 --organization orgakube
osctl inject kubernetes --crt orgakube.crt --key orgakube.key master.yaml
```

And the command that I used for generating the raw image:
```
docker run --rm -it -v /dev:/dev -v $PWD:/out --privileged autonomy/talos:latest image -l -f -p bare-metal -u http://192.168.1.51:8000/master.yaml
```

Here is the configuration file served by the web server: https://hastebin.com/razesiyiga.yaml (I know I shouldn't publicly post the config file but it's just a test).

When starting the VM after a few seconds it crash and reboot itself, here is an imgur video because I couldn't copy the text: https://imgur.com/a/V5CFeqS

What did I go wrong?

I've Slack and my email is the same as the one on my profile picture.

**Comment by andrewrynhard** [comment]
@unixfox Invite to slack has been sent. I'm looking into your setup now 👍.

**Comment by andrewrynhard** [comment]
At a quick glance. This is just a failure on my part! The docs look outdated :(.

**Comment by andrewrynhard** [comment]
See #359.
