### ISSUE TITLE
Make fails on linux kernel >= 4.19

### ISSUE THREAD

**Issue by crodetsky** [autonomy/talos#373]
Attempts to build Talos on Manjaro with kernel version 4.20.7 consistently failing at the `go mod download` step:
```
#43 [base 23/24] RUN go mod download
#43       digest: sha256:ee7fe52b0f7a313a046006d25df18cc847ad8fd86cd90b7b0f9c6d316b2627bd
#43         name: "[base 23/24] RUN go mod download"
#43      started: 2019-02-18 06:52:13.181552568 +0000 UTC
#43    completed: 2019-02-18 06:52:13.473005368 +0000 UTC
#43     duration: 291.4528ms
#43        error: "executor failed running [/toolchain/bin/bash -c go mod download]: exit code: 139"

error: failed to solve: rpc error: code = Unknown desc = executor failed running [/toolchain/bin/bash -c go mod download]: exit code: 139
```
Seeing the following in `dmesg`:
```
[  500.888899] 12693 (go): Uhuuh, elf segment at 0000000000401000 requested but the memory is mapped already
```

I then rolled back to a 4.9.0 kernel and the build completed without issue.

To rule out anything related to the distribution I duplicated this issue on Ubuntu Bionic with kernel 4.19.0 and 4.20.7 kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/

Various reports of similar behavior from other projects end up pointing to this commit:
https://github.com/torvalds/linux/commit/a4ff8e8620d3f4f50ac4b41e8067b7d395056843

Based on this I believe this actually happens on 4.17+ but I have not tested on 4.17 at this point.

**Comment by TimJones** [comment]
Can confirm that I had the same issue on `4.20.10` and after downgrading to `4.18.16`.

I also had problems with the `overlay` driver throwing these errors:
```overlayfs: upperdir is in-use by another mount, mount with '-o index=off' to override exclusive upperdir protection.```
This points to this issue moby/moby#34672 with the [following workaround](https://github.com/moby/moby/issues/34672#issuecomment-350686615).

**Comment by TimJones** [comment]
Can confirm that I had the same issue on `4.20.10` and after downgrading to `4.18.16`.

I also had problems with the `overlay` driver throwing these errors:
```overlayfs: upperdir is in-use by another mount, mount with '-o index=off' to override exclusive upperdir protection.```
This points to this issue moby/moby#34672 with the [following workaround](https://github.com/moby/moby/issues/34672#issuecomment-350686615).

**Comment by andrewrynhard** [comment]
@remyabel Mind posting what version kernel you are running along with info on your distro/setup?

**Comment by remyabel** [comment]
Fedora 29, Docker CE 18.09.2 using overlay2. The workaround above mentions turning index off, but it's already disabled for me.

```
cat /sys/module/overlay/parameters/index
N
```

**Comment by andrewrynhard** [comment]
Yeah I think we found that the workaround didn't work for us too. @TimJones correct me if I'm wrong.

**Comment by TimJones** [comment]
@andrewrynhard Yes I believe I actually ran into 2 separate issues which muddied the waters.
As @remyabel states originally I had to spin up a Debian Stable (with kernel 4.9.0) to get the build working.

**Comment by remyabel** [comment]
You mean @crodetsky.

**Comment by remyabel** [comment]
So turns out that the issue is within gcompat: https://github.com/AdelieLinux/gcompat/commit/d186323a2db1f8bf65b24236ce8d2ddff1b4385a

The above commit fixes the exact error message in the OP. The only problem is that `-static-pie` doesn't seem to be supported with the compiler provided with `autonomy/toolchain`, so that will need to be updated.

**Comment by andrewrynhard** [comment]
@remyabel Awesome. This is worth us prioritizing. I would hate to lose contributors because the build is broken. Appreciate you looking into this!
