### ISSUE TITLE
docker run autonomy/talos:latest doesn't throw error even if master.yaml url is unavailable

### ISSUE THREAD

**Issue by vbmade2000** [autonomy/talos#386]
I am trying to execute following command as mentioned in https://talos.autonomy.io/examples/kvm/

```
docker run \
 --rm \
 --privileged \
 --volume /dev:/dev \
 autonomy/talos:latest image -b /dev/sdb -f -p bare-metal -u http://${IP}:8080/master.yaml
```

**Actual output:**
While executing I found that http://${IP}:8080/worker.yaml was not available because I forgot to put IP there and to start web server exposing http://${IP}:8080/master.yaml but the command finished successfully and didn't throw error.

**Expected output:**
Ideally it should throw an error or show warning if URL is unavailable.

**Comment by andrewrynhard** [comment]
@vbmade2000 Thanks for creating this issue. I think a warning is the way to go here.

**Comment by andrewrynhard** [comment]
Closing. See #398.
