### ISSUE TITLE
Update contributing guide

### ISSUE THREAD

**Issue by andrewrynhard** [autonomy/talos#393]
Looking at [buildkit](https://github.com/moby/buildkit/blob/master/.github/CONTRIBUTING.md) as an inspiration, we need a lot more to help guide contributors.

**Comment by unixfox** [comment]
And don't forget to tell that the contributor needs to sign his commit :).

**Comment by andrewrynhard** [comment]
> And don't forget to tell that the contributor needs to sign his commit :).

:D
