### ISSUE TITLE
Ensure all required kubelet mount points exists

### ISSUE THREAD

**Issue by andrewrynhard** [autonomy/talos#397]
It might be good to double check how we run the kubelet in Talos against this: https://github.com/kubernetes/kubernetes/issues/74148#issuecomment-465627802

**Comment by bradbeam** [comment]
Comparing against the list there's a few deltas with regards to what is being shared with the container -- 

- instances of additional binaries and libraries being mounted up ( mkfs.xfs / iscsiadm )
- host ssl certs
- cni config + binaries

I could see a case for sharing host ssl certs with hyperkube, but the additional binaries seem redundant ( hyperkube already contains mkfs.xfs/ext{2,3,4} ) along with the most recent cni release at the time the hyperkube version was released ( so perhaps we can trim that out of our rootfs ( https://github.com/autonomy/talos/blob/master/Dockerfile#L171-L174 ).
