### ISSUE TITLE
Support loading talos config from specified file

### ISSUE THREAD

**Issue by TimJones** [autonomy/talos#412]
It would help (certainly during alpha development) to have a `--talos-config` argument for `osctl` rather than to rely on the predetermined `~/.talos/config`.

**Comment by andrewrynhard** [comment]
`--talos-config` sounds find by me, but what do you think of just `--config` since there isn't another config that we nee distinguish from?

**Comment by TimJones** [comment]
It was just to be closer to `kubectl` as it uses `--kubeconfig`, and most K8S tools I know also use that standard.

**Comment by andrewrynhard** [comment]
Not a bad idea since we are so aligned with Kubernetes. Updating my PR.
